[package]
name = "filehandle"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.12"
aes = "0.7"
block-modes = "0.8"
hex = "0.4"
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.11"
rand = "0.8.5"
